import type { ItineraryItem, OntologyGroup, Place, Source } from './types'

export const sources: Source[] = [
  {
    id: 'arima-hotel',
    label: '施設・金泉／銀泉',
    publisher: 'ホテルハーヴェスト有馬六彩',
    url: 'https://www.resorthotels109.com/arima/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'arima-access',
    label: 'アクセス・ウェルカムバス',
    publisher: 'ホテルハーヴェスト有馬六彩',
    url: 'https://www.resorthotels109.com/arima/access/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'arima-restaurant',
    label: 'レストラン・夕食料金',
    publisher: 'ホテルハーヴェスト有馬六彩',
    url: 'https://www.resorthotels109.com/arima/restaurant/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'arima-plan',
    label: '宿泊プラン・予約情報',
    publisher: '東急ハーヴェストクラブ',
    url: 'https://www.harvestclub.com/Un/Hotel/Ar/plan.html',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'schema-org',
    label: 'Travel and place vocabulary',
    publisher: 'Schema.org',
    url: 'https://schema.org/docs/full.html',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'gtfs',
    label: 'GTFS Schedule reference',
    publisher: 'MobilityData / GTFS',
    url: 'https://gtfs.org/documentation/schedule/reference/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'prov-o',
    label: 'PROV-O provenance ontology',
    publisher: 'W3C',
    url: 'https://www.w3.org/TR/prov-o/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'postgres-partitioning',
    label: 'Table partitioning',
    publisher: 'PostgreSQL Global Development Group',
    url: 'https://www.postgresql.org/docs/current/ddl-partitioning.html',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'postgis',
    label: 'PostGIS manual',
    publisher: 'PostGIS Project',
    url: 'https://postgis.net/docs/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
]

export const places: Place[] = [
  {
    id: 'arima-roku',
    name: 'ホテルハーヴェスト有馬六彩',
    eyebrow: '自家源泉の温泉宿',
    kind: 'stay',
    area: '有馬温泉・有馬町',
    description: '露天の金泉と大浴場の銀泉。駅から無料ウェルカムバスで約5分。',
    tags: ['金泉', '銀泉', '静けさ', '料理', '送迎'],
    priceLabel: '2食付プラン例 27,500円',
    confidence: 'verified',
    sourceIds: ['arima-hotel', 'arima-access', 'arima-plan'],
    map: { x: 70, y: 23 },
    accent: 'blue',
  },
  {
    id: 'arima-station',
    name: '有馬温泉駅',
    eyebrow: '大阪からの玄関口',
    kind: 'transport',
    area: '神戸電鉄・有馬線',
    description: '大阪・梅田から高速バス約55分。到着後は無料送迎でホテルへ。',
    tags: ['バス', '送迎', '徒歩', '乗換なし'],
    confidence: 'verified',
    sourceIds: ['arima-access'],
    map: { x: 25, y: 62 },
    accent: 'lilac',
  },
  {
    id: 'arima-town',
    name: '有馬温泉街',
    eyebrow: '坂の温泉街',
    kind: 'culture',
    area: '有馬町・太閤橋周辺',
    description: 'チェックイン前後に歩ける、温泉街と路地の散策候補。',
    tags: ['町歩き', '徒歩', '食べ歩き', '歴史'],
    confidence: 'watch',
    sourceIds: ['arima-access'],
    map: { x: 43, y: 48 },
    accent: 'apricot',
  },
  {
    id: 'altura',
    name: 'ALTURA トラットリア＆ブッフェ',
    eyebrow: '館内ブッフェ',
    kind: 'food',
    area: '有馬六彩・館内',
    description: '夕食ブッフェは大人7,260円から。外出せず館内で完結しやすい。',
    tags: ['ブッフェ', '夕食', '価格を抑える', '予約'],
    priceLabel: '夕食 7,260円〜',
    confidence: 'verified',
    sourceIds: ['arima-restaurant'],
    map: { x: 72, y: 53 },
    accent: 'rose',
  },
  {
    id: 'zui',
    name: '瑞（Zui）コースダイニング',
    eyebrow: '館内コース料理',
    kind: 'food',
    area: '有馬六彩・館内',
    description: '和食会席Roka、イタリアンSeionは各14,850円。静かな夕食候補。',
    tags: ['会席', 'イタリアン', '静けさ', '要予約'],
    priceLabel: 'コース 14,850円〜',
    confidence: 'verified',
    sourceIds: ['arima-restaurant'],
    map: { x: 79, y: 39 },
    accent: 'mint',
  },
  {
    id: 'arima-gin-no-yu',
    name: '有馬六彩の銀泉・金泉',
    eyebrow: '館内温泉',
    kind: 'nature',
    area: '有馬六彩・大浴場',
    description: '大浴場は銀泉、露天風呂は金泉。滞在中の入浴を主目的にできる。',
    tags: ['温泉', '金泉', '銀泉', '露天'],
    confidence: 'verified',
    sourceIds: ['arima-hotel'],
    map: { x: 61, y: 30 },
    accent: 'blue',
  },
]

export const itinerary: ItineraryItem[] = [
  { id: 'i1', day: 1, time: '09:00', title: '大阪・梅田を出発', meta: '高速バス・約55分（便は予約時確認）', mode: 'bus', status: 'check', placeId: 'arima-station', sourceIds: ['arima-access'] },
  { id: 'i2', day: 1, time: '10:10', title: '有馬温泉駅 → 有馬六彩', meta: '無料ウェルカムバス・約5分／到着後にホテルへ連絡', mode: 'bus', status: 'fixed', placeId: 'arima-roku', sourceIds: ['arima-access'] },
  { id: 'i3', day: 1, time: '12:00', title: '有馬温泉街を散策', meta: '太閤橋周辺で昼食・町歩き', mode: 'walk', status: 'flex', placeId: 'arima-town', sourceIds: ['arima-access'] },
  { id: 'i4', day: 1, time: '15:00', title: '有馬六彩へチェックイン', meta: '大浴場の銀泉と露天の金泉へ', mode: 'stay', status: 'check', placeId: 'arima-gin-no-yu', sourceIds: ['arima-hotel'] },
  { id: 'i5', day: 1, time: '18:00', title: '館内で夕食', meta: 'ALTURAブッフェ 7,260円〜／外出不要', mode: 'stay', status: 'check', placeId: 'altura', sourceIds: ['arima-restaurant'] },
  { id: 'i6', day: 2, time: '09:00', title: '朝食と朝風呂', meta: '館内ブッフェ 3,300円／温泉を優先', mode: 'stay', status: 'check', placeId: 'arima-roku', sourceIds: ['arima-restaurant', 'arima-hotel'] },
  { id: 'i7', day: 2, time: '13:00', title: '有馬温泉街をゆっくり歩く', meta: '混雑を避けて午後の短時間散策', mode: 'walk', status: 'flex', placeId: 'arima-town', sourceIds: ['arima-access'] },
  { id: 'i8', day: 2, time: '18:00', title: '静かなコース夕食', meta: '瑞（Zui）Roka／Seion・各14,850円', mode: 'stay', status: 'check', placeId: 'zui', sourceIds: ['arima-restaurant'] },
  { id: 'i9', day: 3, time: '09:00', title: '最後の金泉・銀泉', meta: 'チェックアウト前に入浴', mode: 'stay', status: 'fixed', placeId: 'arima-gin-no-yu', sourceIds: ['arima-hotel'] },
  { id: 'i10', day: 3, time: '11:00', title: '有馬六彩 → 大阪', meta: '有馬温泉駅へ送迎後、高速バス', mode: 'bus', status: 'check', placeId: 'arima-station', sourceIds: ['arima-access'] },
]

export const ontologyGroups: OntologyGroup[] = [
  {
    name: 'Place',
    color: 'mint',
    description: '世界の「どこ」を表す地理レイヤー',
    entities: ['Place', 'AdministrativeArea', 'POI', 'Geometry'],
    connectsTo: ['Supply', 'Mobility', 'Evidence'],
  },
  {
    name: 'Supply',
    color: 'rose',
    description: '泊まる・体験する・買う選択肢',
    entities: ['Accommodation', 'Room', 'Activity', 'Offer', 'Amenity'],
    connectsTo: ['Place', 'Planning', 'Evidence'],
  },
  {
    name: 'Mobility',
    color: 'blue',
    description: '地点を時間つきで結ぶ移動ネットワーク',
    entities: ['Operator', 'Stop', 'Route', 'Service', 'ScheduledCall'],
    connectsTo: ['Place', 'Planning', 'Evidence'],
  },
  {
    name: 'Planning',
    color: 'lilac',
    description: '人の希望を実行可能な旅程へ変換',
    entities: ['Trip', 'Party', 'Preference', 'Constraint', 'ItineraryItem'],
    connectsTo: ['Supply', 'Mobility', 'Evidence'],
  },
  {
    name: 'Evidence',
    color: 'apricot',
    description: 'いつ・誰が・何を言ったかを保存',
    entities: ['Source', 'Claim', 'Observation', 'Validity', 'ExternalId'],
    connectsTo: ['Place', 'Supply', 'Mobility', 'Planning'],
  },
]
