import type { ItineraryItem, OntologyGroup, Place, Source } from './types'

export const sources: Source[] = [
  {
    id: 'sado-bus',
    label: '2026年 路線バス時刻表',
    publisher: '新潟交通佐渡',
    url: 'https://www.sado-bus.com/sd/wp-content/uploads/2026/03/jikoku_2604-2611.pdf',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'sado-kisen',
    label: '新潟航路 時刻表・運賃',
    publisher: '佐渡汽船',
    url: 'https://www.sadokisen.co.jp/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'futatsugame',
    label: '宿泊・アクセス情報',
    publisher: 'SADO二ツ亀ビューホテル',
    url: 'https://sfvh.jp/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'oosado',
    label: '宿泊・送迎情報',
    publisher: 'HOTEL OOSADO',
    url: 'https://hotel-oosado.jp/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'jma-aikawa',
    label: '相川 平年値',
    publisher: '気象庁',
    url: 'https://www.data.jma.go.jp/stats/etrn/view/nml_sfc_ym.php?prec_no=54&block_no=47602',
    retrievedAt: '2026-08-01',
    kind: 'climate',
  },
  {
    id: 'schema-org',
    label: 'Travel and place vocabulary',
    publisher: 'Schema.org',
    url: 'https://schema.org/docs/full.html',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'gtfs',
    label: 'GTFS Schedule reference',
    publisher: 'MobilityData / GTFS',
    url: 'https://gtfs.org/documentation/schedule/reference/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'prov-o',
    label: 'PROV-O provenance ontology',
    publisher: 'W3C',
    url: 'https://www.w3.org/TR/prov-o/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'postgres-partitioning',
    label: 'Table partitioning',
    publisher: 'PostgreSQL Global Development Group',
    url: 'https://www.postgresql.org/docs/current/ddl-partitioning.html',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'postgis',
    label: 'PostGIS manual',
    publisher: 'PostGIS Project',
    url: 'https://postgis.net/docs/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
]

export const places: Place[] = [
  {
    id: 'futatsugame-hotel',
    name: 'SADO二ツ亀ビューホテル',
    eyebrow: '北端の一軒宿',
    kind: 'stay',
    area: '鷲崎・二ツ亀',
    description: '全室オーシャンビュー。日没と星空を優先する、静かな1泊目。',
    tags: ['海', '星空', '夕陽', '送迎相談', '2食付き'],
    priceLabel: '空室 △',
    confidence: 'watch',
    sourceIds: ['futatsugame', 'sado-bus'],
    map: { x: 72, y: 12 },
    accent: 'blue',
  },
  {
    id: 'oosado-hotel',
    name: 'HOTEL OOSADO',
    eyebrow: '海辺の温泉宿',
    kind: 'stay',
    area: '相川・春日崎',
    description: '日本海に沈む夕陽と温泉。相川バス停から個別送迎を相談できる。',
    tags: ['温泉', '夕陽', '静けさ', '会席', '送迎相談'],
    priceLabel: '要確認',
    confidence: 'verified',
    sourceIds: ['oosado'],
    map: { x: 22, y: 55 },
    accent: 'rose',
  },
  {
    id: 'futatsugame',
    name: '二ツ亀',
    eyebrow: '海岸・景勝地',
    kind: 'nature',
    area: '鷲崎・二ツ亀',
    description: '透明度の高い海と、潮位で表情を変える二つの島。',
    tags: ['海', '絶景', '徒歩', '朝景色'],
    confidence: 'verified',
    sourceIds: ['futatsugame'],
    map: { x: 80, y: 8 },
    accent: 'mint',
  },
  {
    id: 'ryotsu-port',
    name: '両津港',
    eyebrow: '交通ハブ',
    kind: 'transport',
    area: '両津',
    description: '新潟港からの玄関口。島内バスへの乗り継ぎ基点。',
    tags: ['フェリー', 'バス', '待合', '食事'],
    confidence: 'verified',
    sourceIds: ['sado-kisen', 'sado-bus'],
    map: { x: 70, y: 48 },
    accent: 'lilac',
  },
  {
    id: 'aikawa',
    name: '相川',
    eyebrow: '歴史のまち',
    kind: 'culture',
    area: '相川',
    description: '鉱山文化と海辺の町並みが重なる、西海岸の滞在拠点。',
    tags: ['歴史', '町歩き', '食事', 'バス'],
    confidence: 'verified',
    sourceIds: ['sado-bus'],
    map: { x: 27, y: 52 },
    accent: 'apricot',
  },
  {
    id: 'kitazawa',
    name: '北沢浮遊選鉱場跡',
    eyebrow: '産業遺産',
    kind: 'culture',
    area: '相川',
    description: '巨大なコンクリート遺構。相川滞在と組み合わせやすい。',
    tags: ['歴史', '写真', '夕方'],
    confidence: 'sample',
    sourceIds: [],
    map: { x: 30, y: 48 },
    accent: 'lilac',
  },
]

export const itinerary: ItineraryItem[] = [
  { id: 'i1', day: 1, time: '07:05', title: '大阪（伊丹）を出発', meta: '新潟空港 08:10着', mode: 'flight', status: 'check', sourceIds: [] },
  { id: 'i2', day: 1, time: '09:25', title: '新潟港 → 両津港', meta: 'カーフェリー・11:55着', mode: 'ferry', status: 'fixed', placeId: 'ryotsu-port', sourceIds: ['sado-kisen'] },
  { id: 'i3', day: 1, time: '12:19', title: '両津 → 二ツ亀', meta: '内海府線・13:24着', mode: 'bus', status: 'fixed', placeId: 'futatsugame', sourceIds: ['sado-bus'] },
  { id: 'i4', day: 1, time: '15:00', title: '海と星空の宿へ', meta: '夕食付きで外出不要', mode: 'stay', status: 'check', placeId: 'futatsugame-hotel', sourceIds: ['futatsugame'] },
  { id: 'i5', day: 2, time: '14:24', title: '二ツ亀 → 両津', meta: '内海府線・15:28着', mode: 'bus', status: 'fixed', sourceIds: ['sado-bus'] },
  { id: 'i6', day: 2, time: '16:10', title: '両津 → 相川', meta: '本線・17:08着', mode: 'bus', status: 'fixed', placeId: 'aikawa', sourceIds: ['sado-bus'] },
  { id: 'i7', day: 2, time: '17:20', title: '温泉と夕陽の宿へ', meta: '相川バス停から送迎相談', mode: 'stay', status: 'check', placeId: 'oosado-hotel', sourceIds: ['oosado'] },
  { id: 'i8', day: 3, time: '09:48', title: '相川 → 両津', meta: '本線・10:55着', mode: 'bus', status: 'flex', placeId: 'ryotsu-port', sourceIds: ['sado-bus'] },
  { id: 'i9', day: 3, time: '12:45', title: '両津港 → 新潟港', meta: 'カーフェリー・15:15着', mode: 'ferry', status: 'fixed', sourceIds: ['sado-kisen'] },
]

export const ontologyGroups: OntologyGroup[] = [
  {
    name: 'Place',
    color: 'mint',
    description: '世界の「どこ」を表す地理レイヤー',
    entities: ['Place', 'AdministrativeArea', 'POI', 'Geometry'],
    connectsTo: ['Supply', 'Mobility', 'Evidence'],
  },
  {
    name: 'Supply',
    color: 'rose',
    description: '泊まる・体験する・買う選択肢',
    entities: ['Accommodation', 'Room', 'Activity', 'Offer', 'Amenity'],
    connectsTo: ['Place', 'Planning', 'Evidence'],
  },
  {
    name: 'Mobility',
    color: 'blue',
    description: '地点を時間つきで結ぶ移動ネットワーク',
    entities: ['Operator', 'Stop', 'Route', 'Service', 'ScheduledCall'],
    connectsTo: ['Place', 'Planning', 'Evidence'],
  },
  {
    name: 'Planning',
    color: 'lilac',
    description: '人の希望を実行可能な旅程へ変換',
    entities: ['Trip', 'Party', 'Preference', 'Constraint', 'ItineraryItem'],
    connectsTo: ['Supply', 'Mobility', 'Evidence'],
  },
  {
    name: 'Evidence',
    color: 'apricot',
    description: 'いつ・誰が・何を言ったかを保存',
    entities: ['Source', 'Claim', 'Observation', 'Validity', 'ExternalId'],
    connectsTo: ['Place', 'Supply', 'Mobility', 'Planning'],
  },
]
