import type { ItineraryItem, OntologyGroup, Place, Source, TripSeed } from './types'

export const sources: Source[] = [
  {
    id: 'sado-bus',
    label: '2026年 路線バス時刻表',
    publisher: '新潟交通佐渡',
    url: 'https://www.sado-bus.com/sd/wp-content/uploads/2026/03/jikoku_2604-2611.pdf',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'sado-kisen',
    label: '新潟航路 時刻表・運賃',
    publisher: '佐渡汽船',
    url: 'https://www.sadokisen.co.jp/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'futatsugame',
    label: '宿泊・アクセス情報',
    publisher: 'SADO二ツ亀ビューホテル',
    url: 'https://sfvh.jp/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'oosado',
    label: '宿泊・送迎情報',
    publisher: 'HOTEL OOSADO',
    url: 'https://hotel-oosado.jp/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'jma-aikawa',
    label: '相川 平年値',
    publisher: '気象庁',
    url: 'https://www.data.jma.go.jp/stats/etrn/view/nml_sfc_ym.php?prec_no=54&block_no=47602',
    retrievedAt: '2026-08-01',
    kind: 'climate',
  },
  {
    id: 'schema-org',
    label: 'Travel and place vocabulary',
    publisher: 'Schema.org',
    url: 'https://schema.org/docs/full.html',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'gtfs',
    label: 'GTFS Schedule reference',
    publisher: 'MobilityData / GTFS',
    url: 'https://gtfs.org/documentation/schedule/reference/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'prov-o',
    label: 'PROV-O provenance ontology',
    publisher: 'W3C',
    url: 'https://www.w3.org/TR/prov-o/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'postgres-partitioning',
    label: 'Table partitioning',
    publisher: 'PostgreSQL Global Development Group',
    url: 'https://www.postgresql.org/docs/current/ddl-partitioning.html',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'postgis',
    label: 'PostGIS manual',
    publisher: 'PostGIS Project',
    url: 'https://postgis.net/docs/',
    retrievedAt: '2026-08-01',
    kind: 'standard',
  },
  {
    id: 'sannomiya-rei',
    label: 'アクセス・宿泊情報',
    publisher: '神戸三宮 東急REIホテル',
    url: 'https://www.tokyuhotels.co.jp/kobesannomiya-r/access/index.html',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'arima-tourism-access',
    label: '有馬温泉 交通アクセス',
    publisher: '一般財団法人神戸観光局',
    url: 'https://www.arima-onsen.com/access/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'arima-kin',
    label: '有馬本温泉 金の湯',
    publisher: '兵庫県公式観光サイト 兵庫観光ナビ',
    url: 'https://www.hyogo-tourism.jp/spot/detail_1028.html',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'hankyu-arima',
    label: '有馬温泉－大阪 時刻表・運賃',
    publisher: '阪急観光バス',
    url: 'https://www.hankyu-kankobus.co.jp/highway/timetable/AO/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'arima-hotel',
    label: '施設・金泉／銀泉',
    publisher: 'ホテルハーヴェスト有馬六彩',
    url: 'https://www.resorthotels109.com/arima/',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
  {
    id: 'arima-plan',
    label: '宿泊プラン・予約情報',
    publisher: '東急ハーヴェストクラブ',
    url: 'https://www.harvestclub.com/Un/Hotel/Ar/plan.html',
    retrievedAt: '2026-08-01',
    kind: 'official',
  },
]

export const places: Place[] = [
  {
    id: 'futatsugame-hotel',
    name: 'SADO二ツ亀ビューホテル',
    eyebrow: '北端の一軒宿',
    kind: 'stay',
    area: '鷲崎・二ツ亀',
    description: '全室オーシャンビュー。日没と星空を優先する、静かな1泊目。',
    tags: ['海', '星空', '夕陽', '送迎相談', '2食付き'],
    priceLabel: '空室 △',
    confidence: 'watch',
    sourceIds: ['futatsugame', 'sado-bus'],
    map: { x: 72, y: 12 },
    accent: 'blue',
  },
  {
    id: 'oosado-hotel',
    name: 'HOTEL OOSADO',
    eyebrow: '海辺の温泉宿',
    kind: 'stay',
    area: '相川・春日崎',
    description: '日本海に沈む夕陽と温泉。相川バス停から個別送迎を相談できる。',
    tags: ['温泉', '夕陽', '静けさ', '会席', '送迎相談'],
    priceLabel: '要確認',
    confidence: 'verified',
    sourceIds: ['oosado'],
    map: { x: 22, y: 55 },
    accent: 'rose',
  },
  {
    id: 'futatsugame',
    name: '二ツ亀',
    eyebrow: '海岸・景勝地',
    kind: 'nature',
    area: '鷲崎・二ツ亀',
    description: '透明度の高い海と、潮位で表情を変える二つの島。',
    tags: ['海', '絶景', '徒歩', '朝景色'],
    confidence: 'verified',
    sourceIds: ['futatsugame'],
    map: { x: 80, y: 8 },
    accent: 'mint',
  },
  {
    id: 'ryotsu-port',
    name: '両津港',
    eyebrow: '交通ハブ',
    kind: 'transport',
    area: '両津',
    description: '新潟港からの玄関口。島内バスへの乗り継ぎ基点。',
    tags: ['フェリー', 'バス', '待合', '食事'],
    confidence: 'verified',
    sourceIds: ['sado-kisen', 'sado-bus'],
    map: { x: 70, y: 48 },
    accent: 'lilac',
  },
  {
    id: 'aikawa',
    name: '相川',
    eyebrow: '歴史のまち',
    kind: 'culture',
    area: '相川',
    description: '鉱山文化と海辺の町並みが重なる、西海岸の滞在拠点。',
    tags: ['歴史', '町歩き', '食事', 'バス'],
    confidence: 'verified',
    sourceIds: ['sado-bus'],
    map: { x: 27, y: 52 },
    accent: 'apricot',
  },
  {
    id: 'kitazawa',
    name: '北沢浮遊選鉱場跡',
    eyebrow: '産業遺産',
    kind: 'culture',
    area: '相川',
    description: '巨大なコンクリート遺構。相川滞在と組み合わせやすい。',
    tags: ['歴史', '写真', '夕方'],
    confidence: 'sample',
    sourceIds: [],
    map: { x: 30, y: 48 },
    accent: 'lilac',
  },
  {
    id: 'sannomiya-rei',
    tripId: 'arima-onsen-2026',
    name: '神戸三宮 東急REIホテル',
    eyebrow: '三宮駅前の連泊拠点',
    kind: 'stay',
    area: '神戸・三宮',
    description: 'JR三ノ宮駅東口から徒歩2分。有馬温泉を日帰りにして、2泊とも同じ拠点へ戻る。',
    tags: ['徒歩', '駅近', '連泊', '価格比較', 'バス'],
    priceLabel: '宿泊料金は予約時比較',
    confidence: 'verified',
    sourceIds: ['sannomiya-rei'],
    map: { x: 24, y: 58 },
    accent: 'blue',
  },
  {
    id: 'sannomiya-station',
    tripId: 'arima-onsen-2026',
    name: '三ノ宮駅・三宮駅',
    eyebrow: '連泊と日帰り移動の基点',
    kind: 'transport',
    area: '神戸・三宮',
    description: '大阪から到着し、ホテルと有馬温泉方面への公共交通をつなぐ拠点。',
    tags: ['鉄道', 'バス', '徒歩', '乗換'],
    confidence: 'verified',
    sourceIds: ['sannomiya-rei', 'arima-tourism-access'],
    map: { x: 31, y: 48 },
    accent: 'lilac',
  },
  {
    id: 'arima-station',
    tripId: 'arima-onsen-2026',
    name: '有馬温泉駅',
    eyebrow: '日帰り温泉の玄関口',
    kind: 'transport',
    area: '神戸電鉄・有馬線',
    description: '三宮から公共交通で移動する日帰り側の基点。大阪直通高速バスも公式運行される。',
    tags: ['バス', '鉄道', '徒歩', '車なし'],
    priceLabel: '大阪直通バス 片道1,400円',
    confidence: 'verified',
    sourceIds: ['arima-tourism-access', 'hankyu-arima'],
    map: { x: 76, y: 57 },
    accent: 'lilac',
  },
  {
    id: 'arima-town',
    tripId: 'arima-onsen-2026',
    name: '有馬温泉街',
    eyebrow: '日帰りの町歩き',
    kind: 'culture',
    area: '有馬町・太閤橋周辺',
    description: '宿泊せず、温泉入浴と昼食、路地散策を一日にまとめる。',
    tags: ['町歩き', '徒歩', '食事', '歴史'],
    confidence: 'verified',
    sourceIds: ['arima-tourism-access'],
    map: { x: 66, y: 42 },
    accent: 'apricot',
  },
  {
    id: 'kin-no-yu',
    tripId: 'arima-onsen-2026',
    name: '有馬本温泉 金の湯',
    eyebrow: '公営の日帰り温泉',
    kind: 'nature',
    area: '有馬町',
    description: '有馬温泉駅から徒歩約5分。お盆を含む繁忙日は大人800円で金泉に入浴できる。',
    tags: ['温泉', '金泉', '徒歩', '日帰り'],
    priceLabel: '繁忙日 大人800円',
    confidence: 'verified',
    sourceIds: ['arima-kin'],
    map: { x: 72, y: 28 },
    accent: 'rose',
  },
  {
    id: 'arima-roku',
    tripId: 'arima-onsen-2026',
    name: 'ホテルハーヴェスト有馬六彩',
    eyebrow: '高価格帯の比較候補',
    kind: 'stay',
    area: '有馬温泉・有馬町',
    description: '金泉・銀泉を備える宿。今回は価格負担を理由に2連泊の実行旅程から外し、比較候補として保存する。',
    tags: ['温泉', '金泉', '銀泉', '送迎', '比較'],
    priceLabel: '高価格候補・要比較',
    confidence: 'verified',
    sourceIds: ['arima-hotel', 'arima-plan'],
    map: { x: 82, y: 18 },
    accent: 'mint',
  },
]

export const tripCatalog: TripSeed[] = [
  {
    id: 'sado-summer-2026',
    label: '佐渡島 · 8月お盆',
    destination: '佐渡島',
    party: '1名・1室',
    dateLabel: '2泊3日',
    sourceIds: ['sado-bus', 'sado-kisen', 'futatsugame', 'oosado', 'jma-aikawa'],
  },
  {
    id: 'arima-onsen-2026',
    label: '神戸・三宮泊 · 有馬温泉日帰り',
    destination: '神戸・有馬温泉',
    party: '1名・1室',
    dateLabel: '2泊3日',
    sourceIds: ['sannomiya-rei', 'arima-tourism-access', 'arima-kin', 'hankyu-arima', 'arima-hotel', 'arima-plan'],
  },
]

export const itinerary: ItineraryItem[] = [
  { id: 'i1', day: 1, time: '07:05', title: '大阪（伊丹）を出発', meta: '新潟空港 08:10着', mode: 'flight', status: 'check', sourceIds: [] },
  { id: 'i2', day: 1, time: '09:25', title: '新潟港 → 両津港', meta: 'カーフェリー・11:55着', mode: 'ferry', status: 'fixed', placeId: 'ryotsu-port', sourceIds: ['sado-kisen'] },
  { id: 'i3', day: 1, time: '12:19', title: '両津 → 二ツ亀', meta: '内海府線・13:24着', mode: 'bus', status: 'fixed', placeId: 'futatsugame', sourceIds: ['sado-bus'] },
  { id: 'i4', day: 1, time: '15:00', title: '海と星空の宿へ', meta: '夕食付きで外出不要', mode: 'stay', status: 'check', placeId: 'futatsugame-hotel', sourceIds: ['futatsugame'] },
  { id: 'i5', day: 2, time: '14:24', title: '二ツ亀 → 両津', meta: '内海府線・15:28着', mode: 'bus', status: 'fixed', sourceIds: ['sado-bus'] },
  { id: 'i6', day: 2, time: '16:10', title: '両津 → 相川', meta: '本線・17:08着', mode: 'bus', status: 'fixed', placeId: 'aikawa', sourceIds: ['sado-bus'] },
  { id: 'i7', day: 2, time: '17:20', title: '温泉と夕陽の宿へ', meta: '相川バス停から送迎相談', mode: 'stay', status: 'check', placeId: 'oosado-hotel', sourceIds: ['oosado'] },
  { id: 'i8', day: 3, time: '09:48', title: '相川 → 両津', meta: '本線・10:55着', mode: 'bus', status: 'flex', placeId: 'ryotsu-port', sourceIds: ['sado-bus'] },
  { id: 'i9', day: 3, time: '12:45', title: '両津港 → 新潟港', meta: 'カーフェリー・15:15着', mode: 'ferry', status: 'fixed', sourceIds: ['sado-kisen'] },
]

export const arimaItinerary: ItineraryItem[] = [
  { id: 'arima-i1', tripId: 'arima-onsen-2026', day: 1, time: '09:00', title: '大阪 → 神戸・三宮', meta: '鉄道で移動。利用便と運賃は予約時に確認', mode: 'bus', status: 'check', placeId: 'sannomiya-station', sourceIds: [] },
  { id: 'arima-i2', tripId: 'arima-onsen-2026', day: 1, time: '10:30', title: '三宮駅前へ荷物を預ける', meta: 'JR三ノ宮駅東口からホテルまで徒歩2分', mode: 'walk', status: 'fixed', placeId: 'sannomiya-rei', sourceIds: ['sannomiya-rei'] },
  { id: 'arima-i3', tripId: 'arima-onsen-2026', day: 1, time: '15:00', title: '三宮で1泊目', meta: '有馬温泉内ではなく、駅前ホテルを2連泊の拠点にする', mode: 'stay', status: 'check', placeId: 'sannomiya-rei', sourceIds: ['sannomiya-rei'] },
  { id: 'arima-i4', tripId: 'arima-onsen-2026', day: 2, time: '08:30', title: '三宮 → 有馬温泉', meta: '公共交通で移動。乗換・時刻は公式アクセスで確認', mode: 'bus', status: 'check', placeId: 'arima-station', sourceIds: ['arima-tourism-access'] },
  { id: 'arima-i5', tripId: 'arima-onsen-2026', day: 2, time: '10:00', title: '有馬温泉街を散策', meta: '昼食と町歩きを日帰り行程へ集約', mode: 'walk', status: 'flex', placeId: 'arima-town', sourceIds: ['arima-tourism-access'] },
  { id: 'arima-i6', tripId: 'arima-onsen-2026', day: 2, time: '13:00', title: '金の湯で日帰り入浴', meta: '繁忙日 大人800円・有馬温泉駅から徒歩約5分', mode: 'stay', status: 'fixed', placeId: 'kin-no-yu', sourceIds: ['arima-kin'] },
  { id: 'arima-i7', tripId: 'arima-onsen-2026', day: 2, time: '16:30', title: '有馬温泉 → 三宮', meta: '夕方に同じホテルへ戻り、宿の移動をなくす', mode: 'bus', status: 'check', placeId: 'sannomiya-station', sourceIds: ['arima-tourism-access'] },
  { id: 'arima-i8', tripId: 'arima-onsen-2026', day: 2, time: '18:00', title: '三宮で2泊目', meta: '夕食は駅周辺で選択し、館内コース料金を回避', mode: 'stay', status: 'flex', placeId: 'sannomiya-rei', sourceIds: ['sannomiya-rei'] },
  { id: 'arima-i9', tripId: 'arima-onsen-2026', day: 3, time: '10:00', title: '神戸市内を短時間散策', meta: '荷物を預けたまま、出発時刻に合わせて調整', mode: 'walk', status: 'flex', placeId: 'sannomiya-station', sourceIds: ['sannomiya-rei'] },
  { id: 'arima-i10', tripId: 'arima-onsen-2026', day: 3, time: '15:00', title: '神戸・三宮 → 大阪', meta: '鉄道で帰着。混雑と指定席の要否を当日確認', mode: 'bus', status: 'check', placeId: 'sannomiya-station', sourceIds: [] },
]

export const ontologyGroups: OntologyGroup[] = [
  {
    name: 'Place',
    color: 'mint',
    description: '世界の「どこ」を表す地理レイヤー',
    entities: ['Place', 'AdministrativeArea', 'POI', 'Geometry'],
    connectsTo: ['Supply', 'Mobility', 'Evidence'],
  },
  {
    name: 'Supply',
    color: 'rose',
    description: '泊まる・体験する・買う選択肢',
    entities: ['Accommodation', 'Room', 'Activity', 'Offer', 'Amenity'],
    connectsTo: ['Place', 'Planning', 'Evidence'],
  },
  {
    name: 'Mobility',
    color: 'blue',
    description: '地点を時間つきで結ぶ移動ネットワーク',
    entities: ['Operator', 'Stop', 'Route', 'Service', 'ScheduledCall'],
    connectsTo: ['Place', 'Planning', 'Evidence'],
  },
  {
    name: 'Planning',
    color: 'lilac',
    description: '人の希望を実行可能な旅程へ変換',
    entities: ['Trip', 'Party', 'Preference', 'Constraint', 'ItineraryItem'],
    connectsTo: ['Supply', 'Mobility', 'Evidence'],
  },
  {
    name: 'Evidence',
    color: 'apricot',
    description: 'いつ・誰が・何を言ったかを保存',
    entities: ['Source', 'Claim', 'Observation', 'Validity', 'ExternalId'],
    connectsTo: ['Place', 'Supply', 'Mobility', 'Planning'],
  },
]
